[package]
name = "ston"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
tokio = { version = "1.45.0" , features = ["sync", "rt", "rt-multi-thread", "macros", "io-util"] }
tokio-serial = "5.4.5"
